modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId = "sns"
version = "${file.jarVersion}"
displayName = "Sacks 'N Such"
logoFile = "sns.png"
authors = "Traister101"
description = '''
An addon for TFC.
'''
[[dependencies.sns]]
modId = "tfc"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
[dependencies.sns.mc-publish]
ignore = false
modrinth = "terrafirmacraft"
curseforge = "terrafirmacraft"

[[dependencies.sns]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.sns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"